CREATE TABLE GRAFFEL(
  ID UUID PRIMARY KEY,
  LATITUDE DOUBLE PRECISION NOT NULL,
  LONGITUDE DOUBLE PRECISION NOT NULL
);

CREATE TABLE TAG(
  ID UUID PRIMARY KEY,
  NAME TEXT NOT NULL,
  GRAFFEL_ID UUID REFERENCES GRAFFEL(ID)
);